### PR TITLE
updated plain text strings to translatable strings

### PR DESCRIPTION
**Pull request by Beee4life**
title says it all :)

### CODE REVIEW

**Comment by Hube2** [comment]
I don't mind pull requests, but can we keep the white space the way I have it set up so that we're not replacing every line? You'll need to set up your editor to not convert tabs to spaces. I use 1 tab for indents.

**Comment by Beee4life** [comment]
I didn't change anything on white space. I just opened it, changed it and pushed it...
just copy my lines and change them in your file so you don't have to merge and aren't bothered by whitespace...

How was I supposed to know what your setting is :)

**Comment by Beee4life** [comment]
just copy my lines and change them in your file so you don't have to merge and aren't bothered by whitespace...

**Comment by Hube2** [comment]
Sorry, thanks for taking the time to help out. I didn't mean to come off as rude or anything, just that it's hard to find what I'm looking for when every line is marked as -/+. Just meant that if it's possible you should turn off the feature in your editor that automatically converts coding style. To be honest, I would even care if the lines you change use spaces instead of tabs, but with every line changed, if it was a really big file I'd never be able to find the changes.

I'll take a look at the other request in a bit.

**Comment by Beee4life** [comment]
That is indeed my fault.... i had the file locally, then forked it and pasted my code over it. In hindsight not the best move I now understand :)

**Comment by Beee4life** [comment]
I did some more work on it btw... hope you don't mind :) will push it in a bit...

I improved the css enqueue since your doesn't seem to work (not sure why). The elements are not styled as defined. The function admin_head() doesn't seem to be called or so... not sure why but I just moved it to scripts() and used wp_enqueue_style() which does the trick nicely.

For my own site, I don't want the counter to show everywhere... I want to limit field X (for the name) but I don't want to show the counter there (only on text areas).

So I made a small if statement which checks the class of the input field.
If class == acf_counter then show counter. You can also reverse it of course. Always show counter and hide it with a certain class.

It works for me. Not sure if this is the most optimal way, but it does what I want it to do.

**Pull request closed without merging**
