### PR TITLE
update composer/installers to 2.1

### PR DESCRIPTION
**Pull request by jameelmoses**
Hi John, this updates composer/installers to 2.1

### CODE REVIEW

**Comment by jameelmoses** [comment]
@Hube2 thanks for merging! any chance of a new release?

**Comment by Hube2** [comment]
Did you change the plugin version or do I need to do that

**Comment by jameelmoses** [comment]
I didn't do that since I wasn't sure if there was anything else you wanted to do before a release

**Comment by Hube2** [comment]
I figured it out, looked at the changes again. updated version and released

**Pull request merged**
